version: "3.7"

networks:
  # net-alice-kms:
  # net-bob-kms:
  net-alice:
  net-bob:
  net-public:

services:

  # kmsAlice:
  #   command: start --config /root/tmkms_alice/tmkms.toml -v
  #   container_name: kmsAlice
  #   image: tmkms_alice
  #   networks:
  #     - net-alice-kms
  #   volumes:
  #     - ./kmsAlice:/root/tmkms_alice

  # kmsBob:
  #   command: start --config /root/tmkms_bob/tmkms.toml -v
  #   container_name: kmsBob
  #   image: tmkms_bob
  #   networks:
  #     - net-bob-kms
  #   volumes:
  #     - ./kmsBob:/root/tmkms_bob   

  valAlice:
    command: start --api.enable --api.swagger --home /root/.layer/valAlice
    container_name: valAlice
    # depends_on:
    #   - kmsAlice
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/valAlice
    networks:
      #- net-alice-kms
      - net-alice
    volumes:
      - ./valAlice:/root/.layer

  sentryAlice:
    command: start --api.enable --api.swagger --home /root/.layer/sentryAlice --price-daemon-enabled=false
    container_name: sentryAlice
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/sentryAlice
    networks:
      - net-alice
      - net-public
    volumes:
      - ./sentryAlice:/root/.layer

  valBob:
    command: start --api.enable --api.swagger --home /root/.layer/valBob
    container_name: valBob
    image: layerd_i
    # depends_on:
    #   - kmsBob
    environment:
      - LAYERD_NODE_HOME=/root/.layer/valBob
    networks:
      #- net-bob-kms
      - net-bob
    volumes:
      - ./valBob:/root/.layer

  sentryBob:
    command: start --api.enable --api.swagger --home /root/.layer/sentryBob --price-daemon-enabled=false
    container_name: sentryBob
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/sentryBob
    networks:
      - net-bob
      - net-public
    volumes:
      - ./sentryBob:/root/.layer

  nodeCarol:
    command: start --api.enable --api.swagger --home /root/.layer/nodeCarol --price-daemon-enabled=false
    container_name: nodeCarol
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/nodeCarol
    networks:
      - net-public
    ports:
      - 0.0.0.0:26657:26657
    volumes:
      - ./nodeCarol:/root/.layer