version: "3.7"

services:  
  valAlice:
    command: start --api.enable --api.swagger --home /root/.layer/valAlice
    container_name: valAlice
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/valAlice
    networks:
      - net-alice
    volumes:
      - ./valAlice:/root/.layer

  sentryAlice:
    command: start --api.enable --api.swagger --home /root/.layer/sentryAlice --price-daemon-enabled=false
    container_name: sentryAlice
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/sentryAlice
    networks:
      - net-alice
      - net-public
    volumes:
      - ./sentryAlice:/root/.layer

  valBob:
    command: start --api.enable --api.swagger --home /root/.layer/valBob
    container_name: valBob
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/valBob
    networks:
      - net-bob
    volumes:
      - ./valBob:/root/.layer

  sentryBob:
    command: start --api.enable --api.swagger --home /root/.layer/sentryBob --price-daemon-enabled=false
    container_name: sentryBob
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/sentryBob
    networks:
      - net-bob
      - net-public
    volumes:
      - ./sentryBob:/root/.layer

  nodeCarol:
    command: start --api.enable --api.swagger --home /root/.layer/nodeCarol --price-daemon-enabled=false
    container_name: nodeCarol
    image: layerd_i
    environment:
      - LAYERD_NODE_HOME=/root/.layer/nodeCarol
    networks:
      - net-public
    ports:
      - 127.0.0.1:26657:26657
      - 127.0.0.1:1317:1317
    volumes:
      - ./nodeCarol:/root/.layer

networks:
  net-alice:
  net-bob:
  net-public:
